### ISSUE TITLE
Desafio: Implementar a estatística da meia-vida.

### ISSUE THREAD

**Issue by Vido** [Vido/zecontinha#3]
Implementar a estatística da meia-vida.

Aqui está um exemplo de como o calculo deve ser feito.
https://gist.github.com/Vido/cca498b80f925baaaf96f8d4620d960d
Essa função pode ser escrita no arquivo `coint/cointegration.py`

### models.py
Esta estatística deve ser armazenada no objeto ´CointParams´. É necessário adicionar um campo novo, pode ser chamada do `half_life`. Lembre-se de criar as migrações necessárias

### b3_calc.py
A chamada da função deve ser feita dentro da função `coint_model`
O retorno da função deve ser armazenado no bando de dado pela função `create_cointparams`. Lembre que o sistema compartilha essa função entre os dados da B3 e da Binance.

### Frontend
Para exibir na tela, deve-se acionar uma coluna nova na tabela do arquivo. `dashboard/templates/dashboard/pair_stats.html`

**Comment by SeaSkyThe** [comment]
Atribui a issue pra mim pf
